name: CI

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches: 
      - master
      - 'release/**'

env:
  PLATFORM: Docker Engine - WAGO (Community)
  DEFAULT_PRODUCT_LICENSE: Community Engine
  DOCKER_GITCOMMIT: ${{ github.sha }}
  DOCKER_EXPERIMENTAL: 1
  DOCKER_GRAPHDRIVER: overlay2
  BUILDKIT_PROGRESS: plain
  BASE_DEBIAN_DISTRO: buster
  GO_VERSION: 1.16.7
  APT_MIRROR: cdn-fastly.deb.debian.org
  CHECK_CONFIG_COMMIT: 78405559cfe5987174aa2cb6463b9b2c1b917255
  TESTDEBUG: 0
  TIMEOUT: 120m
  BUILD_OUTPUT: build
  VERSION: '20.10-dev'

jobs:
  build-static-binary:
  
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: amd64
          platform: linux/amd64
        - arch: arm32v7
          platform: linux/arm/v7

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up node for Docker make
      id: setup-docker-make
      uses: WAGO/docker-actions/setup-docker-make@release/v1.0
      with:
        golang-version: ${{ env.GO_VERSION }}
        base-debian-distro: ${{ env.BASE_DEBIAN_DISTRO }}
        host-arch: ${{ matrix.arch }}
        target-platform: ${{ matrix.platform }}
        check-config-commit: ${{ env.CHECK_CONFIG_COMMIT }}
        project-version: ${{ env.VERSION }}

    - name: Set bundle meta information
      id: set-bundle-info
      run: |
        input_path="${BUILD_OUTPUT}/docker-cli"
        echo "::set-output name=input-path::${input_path}"

    - name: Build binary
      uses: docker/build-push-action@v2
      with:
        target: binary
        context: .
        push: false
        outputs: |
          type=local,dest=${{ steps.set-bundle-info.outputs.input-path }}
        cache-from: type=local,src=${{ steps.setup-docker-make.outputs.buildx-cache }}
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        platforms: |
          ${{ matrix.platform }}
        build-args: |
          APT_MIRROR
          PLATFORM
          DEFAULT_PRODUCT_LICENSE
          DOCKER_GITCOMMIT
          VERSION=${{ steps.setup-docker-make.outputs.version }}
          CGO_ENABLED=1
          GO_VERSION=${{ env.GO_VERSION }}
        load: false

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      env:
        BUILDX_CACHE: ${{ steps.setup-docker-make.outputs.buildx-cache }}
      run: |
        rm -rf "${BUILDX_CACHE}"
        mv /tmp/.buildx-cache-new "${BUILDX_CACHE}"
    
    - name: Create bundle
      id: create-bundle
      env:
        BUNDLE_PLATFORM: ${{ steps.setup-docker-make.outputs.target-platform-id }}
        BUNDLE_INPUT_PATH: ${{ steps.set-bundle-info.outputs.input-path }}
      run: |
        bundle_archive_name="docker-cli-static-${BUNDLE_PLATFORM}.tar"
        bundle_archive="${BUILD_OUTPUT}/${bundle_archive_name}"
        tar -C "${BUNDLE_INPUT_PATH}" -cvf "${bundle_archive}" .
        echo "::set-output name=archive::${bundle_archive}"
        echo "::set-output name=archive-name::${bundle_archive_name}"

    - name: Upload bundle
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.create-bundle.outputs.archive-name }}
        path: ${{ steps.create-bundle.outputs.archive }}
        retention-days: 7    
  
    - name: Print artifact version informations
      env:
        BUNDLE_INPUT_PATH: ${{ steps.set-bundle-info.outputs.input-path }}
      run: |
        "${BUNDLE_INPUT_PATH}/docker" version
